### ISSUE TITLE
Add English

### ISSUE THREAD

**Issue by X3nom** [Viking0001/prsi-in-terminal#1]
Make an English version of at least `readme.md`, ideally of whole program/comments for it to be more accessible to people outside of Czechia.

**Comment by MP3Martin** [comment]
I helped @Viking0001 add this code to GitHub and since the code is also written in Czech and @Viking0001 prefers Czech more, the README file was also written in Czech.

It would be nice if the main README was in English and there was an optional Czech README.

But the code is harder. The solution could be to add English comments to the Czech variables if @Viking0001 still wants the variables to have the same names. But imagine reading code in a completely different natural language _(not programming language)_ that you don't understand and having to look up what the variables mean. I will leave that up to @Viking0001

Btw i replied because he probably doesn't have notifications on or something. I will send him this issue so he can decice.

**Comment by MP3Martin** [comment]
> Make an English version of at least `readme.md`, ideally of whole program/comments for it to be more accessible to people outside of Czechia.

I helped @Viking0001 with adding this code to GitHub and since the code is also written in Czech and @Viking0001 prefers Czech more, the README file was also written in Czech.

It would be nice if the main README was in English and there was an optional Czech README.

But the code is harder. The solution could be to add English comments to the Czech variables if @Viking0001 still wants the variables to have the same names. But imagine reading code in a completely different natural language _(not programming language)_ that you don't understand and having to look up what the variables mean. I will leave that up to @Viking0001

Btw i'm replying because he probably doesn't have notifications on or something. I will send him this issue so he can decice.

**Comment by Viking0001** [comment]
I have translated the README but not the code for me the function "StvorKaru" is perfect. Maybe I'll rewrite the code into English in the future but no promises,
